### ISSUE TITLE
Player HP bar duration

### ISSUE THREAD

**Issue by AlvinSeville** [SimpleMC/SimpleHealthbars2#19]
Hello, i love the plugin, but the problem is a player's HP bar shows only for half a second or even less. The duration of mobs' HP bar is around 5 seconds and that's perfect so it would be cool if the player's HP bar duration was atleast 5 seconds aswell.

**Comment by tajobe** [comment]
Hey there!

Thanks for giving the plugin a try. The player health bar should be 5 seconds as well, but I'll try to look into why it isn't working right.

What is your `player-bar` config (in the `config.yml`)? Also, do you have any other plugins that might be overriding or interfering with the health bar?

**Comment by Momonche** [comment]
I have a similar issue
When a player hit a player, there is no HP under the name
When me (op player) hit a player, I can see the HP for somes seconds

player-bar:
  type: SCOREBOARD
  style: ABSOLUTE

**Comment by Momonche** [comment]
If it would be possible to add more time to the duration, it would be fine

+1

**Comment by tajobe** [comment]
The duration of the bar will be configurable in the future but if the bar isn't staying for the 5 seconds its supposed to, increasing it won't change that. There is likely another plugin that is switching the scoreboard out.

**Comment by Momonche** [comment]
Yeah I just uninstall ScoreboardStats cause of an incompatibility 

Featherboard would be a better option for that issue

**Comment by AlvinSeville** [comment]
Yeah, I just found out it was Stats ScoreBoard 3.1.9-Lite that broke it. I didn't know it has something to do with scoreboards. Is there a way to have both your plugin and a plugin for scoreboard on side of the screen?

**Comment by Momonche** [comment]
Some scoreboards plugins are compatible with other plugins who use scoreboard system
So just check if your plugin is ok with that or ask to the dev

Or like me, find an other plugin compatible :'(

**Comment by tajobe** [comment]
@AlvinSeville 
> Is there a way to have both your plugin and a plugin for scoreboard on side of the screen?

So...kind of. The way it works is that a player can only have a [single scoreboard assigned](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#setScoreboard-org.bukkit.scoreboard.Scoreboard-), however a scoreboard can have multiple objectives, each of which can have a different display slot (either `BELOW_NAME`, `PLAYER_LIST`, `SIDEBAR`). There is a single default [`Main` scoreboard](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scoreboard/ScoreboardManager.html#getMainScoreboard--) that if other plugins are using we can add an objective with the below name display slot and coexist, but if other plugins create their own scoreboard (as SimpleHealthbars2 does currently), they can't be shared. The API leaves a bit to be desired...

What I can do is add a config option for `useMainScoreboard` (defaulted to `true`) to increase the chance that we'll work with other plugins, but there's nothing I can reasonably do if they are creating and setting a new one.

Alternatively, you could try the `ACTION` ~~scoreboard~~ healthbar type if you aren't tied to the scoreboard version.

**Comment by tajobe** [comment]
@AlvinSeville / @Momonche I've added the option I described above in #20. Once released, it will allow you to use the main scoreboard for the player health but because players use that scoreboard by default, the health will always show (assuming there isn't already an objective in the `BELOW_NAME` slot). That should mean any other plugins that use the main scoreboard can coexist/render at the same time.

I'll follow up with the ability to configure healthbar duration later.

**Comment by Momonche** [comment]
@tajobe Nice ! Thanks !

**Comment by tajobe** [comment]
Sorry for the delay. I just published version `0.2.0` with the additional `useMainScoreboard` and healthbar `duration` options, please give it a try and let me know if that works for you.

I'll close this issue for now but I can reopen if something isn't covered.

edit: Sorry, here's the link: https://github.com/SimpleMC/SimpleHealthbars2/releases/tag/release-0.2.0

**Comment by Momonche** [comment]
Seems to work, thanks @tajobe !
